﻿#BNF+IAT 1.0 UTF-8;
!grammar call;


!slot <motion>;
!slot <item>;
!slot <who>;
!slot <number>;
!slot <unit>;

!start <callstart>;
<callstart>:[<who>]<choose>[<distance>];
<who>:左手|右手|双手;
<choose>:<motion>[<item>];
<motion>:向上|向下|向前|向后|向左|向右|挥手|握个手|碰拳|和我猜个拳吧|松开|比个|回到初始位置|拿|倒|抓|承让承让;
<item>:水杯|瓶子|水|苹果|箱子|橘子;
<distance>:<number>[<unit>];
<number>:一|二|三|四|五|六|七|八|九|十|欧可|心|耶;
<unit>:厘米|米|公分;
